------------------------------------------------------------
Loading and preprocessing client data...
Loaded dataset from: ./heart.csv
------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB
None
Missing values:
 Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64
Has Duplicates: False
------------------------------------------------------------
Saved boxplot to ./EDA/boxplot.png
------------------------------------------------------------
Removed 216 outlier rows
------------------------------------------------------------
Performed feature engineering
------------------------------------------------------------
Scaled numerical features
------------------------------------------------------------
Selected 23 features: ['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak', 'Sex_F', 'Sex_M', 'ChestPainType_ASY', 'ChestPainType_ATA', 'ChestPainType_NAP', 'ChestPainType_TA', 'RestingECG_LVH', 'RestingECG_Normal', 'RestingECG_ST', 'ExerciseAngina_N', 'ExerciseAngina_Y', 'ST_Slope_Down', 'ST_Slope_Flat', 'ST_Slope_Up', 'AgeGroup_Middle-aged', 'AgeGroup_Senior', 'AgeGroup_Very old']
------------------------------------------------------------
Client ID: 2023
Random seed used: 2023
Malicious client? ❌ NO
Class distribution in this client:
[75 65]
Data shape before augmentation: (140, 23)
------------------------------------------------------------
✅ Client data augmented
New shape: (2000, 23)
New class distribution: [1008  992]
------------------------------------------------------------
Starting Federated Learning Client...
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/loki/Coding/Federated-learning-based-Heart-Disease-Prediction-/fl_client.py", line 172, in <module>
    fl.client.start_client(
    ~~~~~~~~~~~~~~~~~~~~~~^
        server_address="localhost:8080",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        client=client.to_client()  # Convert NumPyClient to standard Client
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/loki/Coding/Federated-learning-based-Heart-Disease-Prediction-/.venv/lib/python3.13/site-packages/flwr/compat/client/app.py", line 184, in start_client
    start_client_internal(
    ~~~~~~~~~~~~~~~~~~~~~^
        server_address=server_address,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
        max_wait_time=max_wait_time,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/loki/Coding/Federated-learning-based-Heart-Disease-Prediction-/.venv/lib/python3.13/site-packages/flwr/compat/client/app.py", line 395, in start_client_internal
    message = receive()
  File "/home/loki/Coding/Federated-learning-based-Heart-Disease-Prediction-/.venv/lib/python3.13/site-packages/flwr/compat/client/grpc_client/connection.py", line 142, in receive
    proto = next(server_message_iterator)
  File "/home/loki/Coding/Federated-learning-based-Heart-Disease-Prediction-/.venv/lib/python3.13/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
           ~~~~~~~~~~^^
  File "/home/loki/Coding/Federated-learning-based-Heart-Disease-Prediction-/.venv/lib/python3.13/site-packages/grpc/_channel.py", line 952, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8080: Failed to connect to remote host: connect: Connection refused (111)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8080: Failed to connect to remote host: connect: Connection refused (111)"}"
>
